import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useRouter } from "next/router";
import axios from 'axios'
import CustomProductDetail from '../../components/CustomProductDetail';





const config = {
  headers: {
    "Content-Type": "application/json",
  },
};

export const getStaticPaths = async () => {

  const res = await axios.get('http://127.0.0.1:8000/store/custom-products/', config);
  const paths = await res.data.map((product) => ({
    params: { id: product.id.toString() },
  }));

  return {
    paths,
    fallback: false,
  };

};

export const getStaticProps = async (ctx) => {

  const product_id = ctx.params?.id;
    
  const response = await axios.get(`http://127.0.0.1:8000/store/custom-products/${product_id}/`, config);

  return {
    props: {
      product: response.data["Product"],
    },
  };
};


export default function CustomProductDetailFunction({product}) {

  const router = useRouter();

  console.log(product)

  return (product == undefined)?<div></div>:(
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CustomProductDetail product={product} />
      </main>
    </div>
  )
}