import Head from 'next/head'
import Image from 'next/image'
import CategoryGrid from '../components/CategoryGrid'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import axios from 'axios'
import { useCart } from '../context/CartContext'

export default function Home() {

  const {cart} = useCart()

  const [categories, setCategories] = useState(null);

    useEffect(async () => {
       getCategories(setCategories);
    }, []);
  
    console.log(cart)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CategoryGrid categories={categories} />
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

const getCategories = (setCategories) => {
  const config = {
    headers: {
      "Content-Type": "application/json",
    },
  };

  const categories_url = 'http://127.0.0.1:8000/' + "store/categories/";
  axios
    .get(categories_url, config)
    .then(async (res) => {
      const result = await res.data;
      setCategories(result);
    })
    .catch((error) => {
      console.log(error);
    });
};

