import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useEffect, useState} from 'react'
import axios from 'axios'
import { useCart } from '../context/CartContext'
import OrderResume from '../components/OrderResume'
import CheckoutForm from '../components/CheckoutForm'
import {
  Col,
  Row,
} from "react-bootstrap";

export default function OrderCheckout() {

  const {cart} = useCart()
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Row>
                <Col xs={12} sm={12} md={12} lg={6}>
        <CheckoutForm />

                </Col>
                <Col xs={12} sm={12} md={12} lg={6}>
                    
        <OrderResume />
                </Col>
            </Row>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

